reactjs/fr.react.dev

content/docs/rendering-elements.md
content/docs/state-and-lifecycle.md
examples/rendering-elements/render-an-element.js
examples/rendering-elements/update-rendered-element.js

👋 Voici ma traduction pour la page https://reactjs.org/docs/rendering-elements.html
Concernant le titre "Rendering Elements", j'ai hésité entre ces traductions : 
**EDIT :** suite à la review de @JeremiePat on est parti sur « Le rendu des éléments »
- Rendre des éléments (pas très français) ;
- Faire le rendu d'éléments (comme proposé par @thib92 dans https://github.com/reactjs/fr.reactjs.org/pull/12, mais je trouve ça un peu lourd) ;
- Rendu d'éléments (celle que je propose).
J'attends vos retours ! 🙂

Traduction de la page "Rendering Elements"

---

content/docs/handling-events.md

Translation of Handling Events

---

content/docs/web-components.md

Bonjour,
Voici ma traduction pour la page sur les [WC](https://reactjs.org/docs/web-components.html) !
ps: je n'ai pas traduit `wrapper`

Web components

---

content/docs/fragments.md

Bonjour ✋ 
Voici ma modeste contribution pour la page sur les [Fragments](https://reactjs.org/docs/fragments.html)
Je pense qu'il y aura des petites remarques  à faire car je ne suis pas sûre de tout, je suis à l'écoute. Merci pour la review !

Translation for "Fragments"

---

content/docs/faq-ajax.md

:books: Translation page FAQ AJAX APIs

---

content/docs/reference-javascript-environment-requirements.md

@tdd Traduction de la page "JS Environment Requirements".
Petit doute sur la traduction de "Hello, world!" en "Bonjour, monde !", j'ai vu que ça a été fait comme ça sur la traduction de la page "Hello, world!".
C'est ma première PR j'espère que je n'ai pas fait d'erreurs ;)

Translation for  "JS Environment Requirements"

---

content/docs/create-a-new-react-app.md
content/docs/handling-events.md
content/docs/introducing-jsx.md
content/docs/state-and-lifecycle.md
content/docs/thinking-in-react.md

Fix merge conflicts

---

content/docs/getting-started.md

@tdd voici ta trad de la page `getting-started`.
Plusieurs points:
- `online playground` traduit en `terrain de jeu en ligne`
Non traduit:
- `Hello world`: "Essayez um modèle Hello World sur CodePen"
- `widgets`: "étendre progressivement sa présence ou la limiter à quelques widgets dynamiques"
Tiens moi au jus.

Getting started

---

content/tutorial/nav.yml
content/tutorial/tutorial.md

@JeremiePat j'aurais vraiment besoin rapidement de ta revue là-dessus, pour boucler 100% du Core ASAP (ça me saoule qu'on n'y soie pas encore, j'avoue).
*(Et au passage, j'attends ton traitement de ma revue pour ta PR #16 sur l'API React 😉)*

Translation of the Tutorial

---

content/docs/reference-react-dom.md

This is the final page for completing Core 100%, therefore releasing.
@JeremiePat it's in your hands now buddy 😉 :
1. Processing my review of #16 — React API
2. Reviewing #81 — Tutorial (long)
3. Reviewing this — ReactDOM API
Then we're good to go on core! I'm tackling more reviews for the Advanced Guides, FAQ, Hooks etc. no later than Tuesday, with a major push throughout the week until Friday.

Translation of the “ReactDOM” API reference page

---

content/docs/hooks-state.md

Using the state hook traduction

---

content/docs/hooks-reference.md

Hello ! :wave: 
Voici un premier jet pour la page https://reactjs.org/docs/hooks-reference.html

Translation: hooks-reference.md in French

---

content/docs/faq-build.md

Désolée @tdd mais je n'ai pas eu l'option de créer une draft pull request ... L'option n'était pas disponible, c'est assez étrange.

 📖 Translation FAQ - Babel, JSX, and Build Steps

---

content/docs/faq-structure.md

Big hesitation between `Existe-t-il` and `Y-a-t-il` also some translations a bit far away from the original sentence structure but I have found them more "real"

Faq structure

---

content/docs/faq-styling.md

Bonjour,
Voici la traduction de FAQ - Styles and CSS.
J'ai une hésitation à traduire ou non `React Transition Group` et `React Motion`.

🌐translation page faq-styling

---

content/docs/optimizing-performance.md

Bonjour,
Voici ma proposition de traduction pour [la page sur les performances](https://reactjs.org/docs/optimizing-performance.html).

Translation of Optimizing Performance page

---

content/docs/nav.yml
content/docs/static-type-checking.md

Voici ma proposition de traduction pour "Static type checking" !
Quelques doutes quant à la terminologie française étant donné que ma langue de travail est l'anglais.

Traduction de Static type checking

---

content/docs/strict-mode.md

This supersedes @erkela's #73 original PR (as they haven't picked up on our review in days) and @sheplu's attempt at creating an alternate PR (that had incorrect lineage).

Strict mode

---

content/blog/2018-03-27-update-on-async-rendering.md
examples/update-on-async-rendering/adding-event-listeners-after.js
examples/update-on-async-rendering/adding-event-listeners-before.js
examples/update-on-async-rendering/adding-event-listeners-create-subscription.js
examples/update-on-async-rendering/fetching-external-data-after.js
examples/update-on-async-rendering/fetching-external-data-before.js
examples/update-on-async-rendering/initializing-state-after.js
examples/update-on-async-rendering/initializing-state-before.js
examples/update-on-async-rendering/invoking-external-callbacks-after.js
examples/update-on-async-rendering/invoking-external-callbacks-before.js
examples/update-on-async-rendering/react-dom-properties-before-update-after.js
examples/update-on-async-rendering/react-dom-properties-before-update-before.js
examples/update-on-async-rendering/side-effects-when-props-change-after.js
examples/update-on-async-rendering/side-effects-when-props-change-before.js
examples/update-on-async-rendering/updating-external-data-when-props-change-after.js
examples/update-on-async-rendering/updating-external-data-when-props-change-before.js
examples/update-on-async-rendering/updating-state-from-props-after.js
examples/update-on-async-rendering/updating-state-from-props-before.js
examples/update-on-async-rendering/using-react-lifecycles-compat.js
src/components/MarkdownPage/MarkdownPage.js
src/pages/blog/all.html.js
src/templates/blog.js
src/utils/toCommaSeparatedList.js

Blog post translation (update on async rendering)

---

content/docs/faq-functions.md

Je n'étais pas sûr de comment traduire toute la partie "throttle" et "debounce", donc j'ai un peu fait de la soupe sur cette partie.
Si quelqu'un a une meilleure traduction des termes techniques de cette partie, je suis ouvert aux suggestions 😄

Translate "Passing functions to components"

---

TRANSLATORS.md

Update translators forresst

---

content/docs/hooks-reference.md

Un petit oubli lors de la traduction

hooks-reference: Traduction oubliée

---

content/community/tools-model-mgmt.md

Hello,
La traduction de la page https://reactjs.org/community/model-management.html

Translate Community/Tools/Model Management page

---

content/community/tools-testing.md

Hello,
Ma traduction de la page https://reactjs.org/community/testing.html.

Translate Community/Tools/Testing page

---

content/community/support.md

🌐 Translation support page

---

content/community/courses.md

Traduction de la page `Cours`, aucun ne possède d'équivalent en Français malheureusement.

 🌐Translation courses

---

content/community/articles.md

 🌐 Translation articles

---

content/community/tools-misc.md

Hello,
Ma traduction pour la page https://reactjs.org/community/misc.html

Translate Community/Tools/Misc page

---

content/community/tools-ui-components.md

Hello,
Voici ma traduction pour https://reactjs.org/community/ui-components.html
(à noter que j'ai remplacé [react-switch-button](https://github.com/gfazioli/react-switch-button) déprécié par [react-toggle](https://github.com/gfazioli/react-toggle).
Il faudrait peut-être le faire aussi sur la page en VO...

Translate Community/Tools/UI Components page

---

content/community/external-resources.md
content/community/videos.md

Translation of the “Community › Resources › Videos / External Resources“ pages

---

content/blog/2017-04-07-react-v15.5.0.md

2017 04 07 react v15.5.0

---

content/docs/hooks-intro.md

Il y avait une petite erreur de traduction dans la page d'introduction aux **Hooks** :wink:

fix: french translation mistake

---

content/blog/2018-12-19-react-v-16-7.md

salut @tdd  je viens de pull request la nouvelle page que vous m'avez assigne.

This Is Not the One With Hooks (Traduction complete)

---

content/docs/forms.md

Typo forms.md

---

content/docs/components-and-props.md

Le mot "en" etait present 2 fois. Merci !

Faute de frappe ligne 92

---

content/blog/2019-08-08-react-v16.9.0.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad pour l’annonce de la 16.9 récemment ajoutée. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…

Translation for the React 16.9 announcement blog post

---

content/docs/concurrent-mode-adoption.md
content/docs/nav.yml

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad pour la page sur l'adoption du mode concurrent, récemment ajoutée. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…

Traduction de la page "Adopter le mode concurrent"

---

content/blog/2019-02-06-react-v16.8.0.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad (due de tellement longue date…) pour le blog de sortie de la 16.8. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…

Traduction de la page de blog React 16.8 (sortie des Hooks)

---

content/blog/2018-11-27-react-16-roadmap.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad (due de si longue date…) pour la feuille de route React 16.x. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…
C’est le dernier contenu dont la traduction était importante (contenu important, lié de plusieurs endroits des docs et autres articles, et visible dans les billets récents du blog). Après ça, on est franchement les plus à jour du monde ! 🎉 😁

Traduction de la feuille de route React 16.x

---

content/docs/getting-started.md

Ajout du 'i' dans le lien ligne 41.

Ajout du 'i' manquant

---

content/docs/lifting-state-up.md

Fix translation on lifting-state-up

---

content/docs/reference-react-component.md

All those links are in fact translated now

remove english langage warning

---

content/blog/2018-08-01-react-v-16-4-2.md

Salut @tdd, voici ma traduction comme convenu !

Traduction de la page “React v16.4.2: Server-side vulnerability fix”

---

content/blog/2016-07-11-introducing-reacts-error-code-system.md

@tdd je ne parviens pas à me rappeler si les messages d'erreurs comme ceux de l'article doivent être traduits ou non ?

 🌐- Translation react error code system

---

content/blog/2016-02-19-new-versioning-scheme.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad pour l’article de blog sur le Profileur. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…
Je suis en train de traduire les articles de blog listés dans l'*issue* centrale (liés 2+ fois depuis les docs) ainsi que certains articles autres mais ayant moins de 2 ans.
Merci !

Traduction de l'article de blog "New versioning scheme"

---

content/blog/2017-09-26-react-v16.0.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad pour l’article de blog sur la sortie de React 16.0. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…
Je suis en train de traduire les articles de blog listés dans l'*issue* centrale (liés 2+ fois depuis les docs) ainsi que certains articles autres mais ayant moins de 2 ans.
Merci !

Traduction FR de l'article de blog "React v16.0"

---

content/docs/web-components.md

Typo fix for web-components.md (être -> êtes)

---

content/docs/create-a-new-react-app.md

syntax mistake - Update create-a-new-react-app.md

---

content/tutorial/tutorial.md

I found it a bit confusing talking about water temperature.

Change expression translation

---

content/blog/2020-08-10-react-v17-rc.md

Fix typo in 2020-08-10-react-v17-rc.md

---

content/docs/hooks-intro.md

It's my first PR, have you a comment for my contribution ? 🙈

fix: fix typo in hooks intro

---

content/versions.yml
src/site-constants.js

I added the latest version to site-constants and links to version pages.

Fixed version number and added new version links to related page

---

content/docs/hooks-reference.md

typo durée de vie *du* composant

---

content/docs/jsx-in-depth.md

Syntax error in french translation of lowercase letter component example.

[docs] Update jsx-in-depth.md

---

content/docs/hello-world.md

"decent" veut plutôt dire "adéquat" ou "suffisant" ou "notable". Son calque français, "décent", est le contraire de "indécent" ce qui est très négatif. Or le but n'est pas d'humilier les gens qui n'auraient pas cette connaissance de base de Javascript.

Improve french translation of "decent"

---

.gitignore
src/components/MDX/Challenges/Challenge.tsx
src/components/MDX/Challenges/Challenges.tsx
src/components/MDX/Challenges/Navigation.tsx
src/components/MDX/ExpandableCallout.tsx
src/components/MDX/ExpandableExample.tsx
src/components/MDX/Recap.tsx
src/components/Tag.tsx
src/content/learn/synchronizing-with-effects.md

These seem stable enough, and localizing them avoid jarring bits of English within French contents.
At any rate, if they evolve in breaking ways, I'll sync.

Localize remaining in-page doc widgets

---

src/components/MDX/MDXComponents.tsx

Le "prêt·e à en apprendre davantage ?" des intros de chapitre.

Encore des trads de widgets stables au sein des pages de docs

---

src/content/reference/react/Fragment.md
src/content/reference/react/components.md

Hello voici ma PR pour la page composants, cette page est assez courte.

Translation of the "react: Components" page

---

src/components/Layout/HomeContent.js
src/components/Layout/TopNav/TopNav.tsx
src/components/SocialBanner.tsx

La core team nous demande de ne pas la traduire davantage pour le moment car ça risque de pas mal bouger (idem pour les layouts et la nav)

Homepage: traduction au-dessus du fold

---

src/components/MDX/Challenges/Challenge.tsx
src/content/learn/synchronizing-with-effects.md
src/sidebarLearn.json

Trad intégrale (pfiou !)
Bon, faut encore que je fasse ma propre repasse intégrale (d'où le statut Draft), mais pour ce genre de mammouths (1500+ lignes), j'apprécierais au moins 2 relectures soignées les copains 😉

Synchronizing with Effects

---

src/content/learn/adding-interactivity.md
src/sidebarHome.json
src/sidebarLearn.json

Translate in french the index of chapter adding interactivity

doc(adding_interactivity): translate in french the index

---

src/content/learn/you-might-not-need-an-effect.md
src/sidebarLearn.json

J'ai déjà fait une repasse complète, mais je suis preneur d'une revue d'ici la fin du week-end en complément, avant publication.

Translation: You might not need an effect

---

src/components/Layout/Toc.tsx
src/utils/prepareMDX.js

This is pretty stable UI, it seems.

UI Translation: in-page TOC sidebar (wide-enough screens)

---

src/sidebarCommunity.json
src/sidebarReference.json

chore(sidebars): sync translated FR headings

---

src/content/learn/separating-events-from-effects.md

Traduction de la page [Separating Events from Effects](https://react.dev/learn/separating-events-from-effects).

doc(separating-events): french translation

---

src/content/learn/escape-hatches.md
src/content/learn/referencing-values-with-refs.md

Je laisse ça là ce weekend si une review vous dit.

Translation of the "Referencing Values With Refs" page

---

src/content/reference/react/useDeferredValue.md

Traduction de la page "useDeferredValue". Étant donné qu'il s'agit de ma première traduction, je vous laisse me donner tous vos meilleurs conseils !

Translation of the 'useDeferredValue' page

---

TRANSLATORS.md

Je pose ça là quelques jours si quelqu'un veut faire une review

Update for TRANSLATORS.md

---

src/content/learn/start-a-new-react-project.md
src/sidebarLearn.json

here you will find the translation of `start-a-new-project-page` page

Translation: Start a New Project

---

src/content/learn/manipulating-the-dom-with-refs.md

Je pose ça là jusqu'au weekend si quelqu'un veut faire une review.

Translation: Manipulating the DOM with refs

---

src/content/learn/render-and-commit.md

Je pose ça là quelques jours si quelqu'un veut faire une review

Translation: Render and Commit

---

src/content/reference/react/apis.md
src/content/reference/react/createContext.md

Translation of the “createContext” page

---

TRANSLATORS.md
src/content/reference/react/index.md
src/content/reference/react/useDebugValue.md

Hello 👋 ! Voici une petite PR pour la traduction de la page reference/react/useDebugValue de la documentation.
Merci encore aux maintainers pour leurs travail 🙏

Translation of the "useDebugValue" page from API references

---

src/content/learn/extracting-state-logic-into-a-reducer.md

Traduction de la page [Extracting State Logic into a Reducer](https://react.dev/learn/extracting-state-logic-into-a-reducer).
J'ai gardé le verbe *dispatcher* tel quel (mais en italique).

Extracting state logic into a reducer

---

src/content/learn/scaling-up-with-reducer-and-context.md

Traduction de la page https://react.dev/learn/scaling-up-with-reducer-and-context

Scaling up with reducer and context

---

src/content/reference/react/lazy.md

hello, here you will find the translation the `lazy` page

translate lazy page

---

src/content/reference/react/useContext.md

Translation of useContext

---

src/content/reference/react/useReducer.md

PR en draft, je n'ai pas encore fait ma propre relecture.

Traduction de useReducer

---

src/content/learn/updating-arrays-in-state.md

Traduction française de la page [Updating Arrays in State](https://react.dev/learn/updating-arrays-in-state).

Translation of the “Updating Arrays in State” page

---

src/content/reference/react-dom/components/textarea.md

Bonjour ! 
Voici ma PR pour `<textarea>`. J'espère m'être améliorée sur celle-ci ! :)

Translation of "<textarea>" page

---

TRANSLATORS.md
src/content/reference/react/StrictMode.md

Traduction de la page [`<StrictMode>`](https://react.dev/reference/react/StrictMode)

translation of StrictMode

---

TRANSLATORS.md
src/content/reference/react-dom/components/input.md

Voici la traduction de la page `<input />`, merci d'avance pour la review ;)

Provide translation of the input page

---

src/content/reference/react-dom/components/form.md
src/content/reference/react-dom/components/input.md
src/content/reference/react-dom/hooks/useFormState.md
src/content/reference/react/useOptimistic.md

Translation of the latest Canary API pages

---

src/content/reference/react/use-server.md

Translation of the fleshed-out 'use server' directive page

---

.vscode/react-dev.code-snippets
src/content/reference/react/use-client.md
src/content/reference/react/use-server.md

Translation of the fleshed-out "use client" directive page

---

src/content/community/versioning-policy.md

Versioning policy

---

src/content/warnings/special-props.md

Hello @tdd, en développant mon site, je suis tombé sur une erreur qui m'a permis d'accéder à cette page. Je me suis permis de rectifier quelques parties.

Chore(Docs): fix typo special-props.md

---

src/content/learn/index.md

fix typo next-steps section

---

src/content/reference/react-dom/hooks/useFormStatus.md

fixed typo in UseFormStatus example

---

src/content/learn/queueing-a-series-of-state-updates.md

Corrected homophone in queueing-a-series-of-state-updates.md

---

src/components/MDX/MDXComponents.tsx
src/content/blog/2024/04/25/react-19-upgrade-guide.md
src/content/blog/2024/04/25/react-19.md
src/content/blog/2024/05/22/react-conf-2024-recap.md
src/content/blog/index.md
src/content/community/docs-contributors.md
src/content/community/team.md
src/content/community/translations.md
src/content/learn/synchronizing-with-effects.md
src/content/reference/react-dom/client/createRoot.md
src/content/reference/react-dom/client/hydrateRoot.md
src/content/reference/react-dom/components/common.md
src/content/reference/react/useDeferredValue.md
src/content/versions.md
src/sidebarBlog.json
src/utils/rss.js

This covers all pages that were already translated and needed updates for all sync-PR-initiated content updates.
Recent *new* pages are not translated yet.

copy: finalize FR updates for most translated pages

---

src/content/blog/2024/05/22/react-conf-2024-recap.md
src/content/reference/react/act.md
src/content/reference/react/useMemo.md
src/content/reference/react/useReducer.md
src/content/reference/react/useState.md
src/content/reference/react/useTransition.md
src/content/reference/rules/components-and-hooks-must-be-pure.md
src/content/reference/rules/index.md
src/content/reference/rules/react-calls-components-and-hooks.md
src/content/reference/rules/rules-of-hooks.md

l10n: first batch of translations for new contents

---

src/components/Layout/HomeContent.js

Hello,
I propose you to update this little typo in the homepage.
Thank you!

docs: update typo in `HomeContent.js`
