content/home/examples/a-component-using-external-plugins.js
content/home/examples/a-component-using-external-plugins.md
content/home/examples/a-simple-component.js
content/home/examples/a-simple-component.md
content/home/examples/a-stateful-component.js
content/home/examples/a-stateful-component.md
content/home/examples/an-application.js
content/home/examples/an-application.md
content/home/marketing/component-based.md
content/home/marketing/declarative.md
content/home/marketing/learn-once-write-anywhere.md
gatsby-config.js
src/components/TitleAndMetaTags/TitleAndMetaTags.js
src/pages/index.js

Proposed translation for the French Hompage of reactjs.org

HomePage translation

---

content/docs/state-and-lifecycle.md

Translated the page "State and Lifecycle" to French.
I didn't translate the page links and the anchor ids, as I didn't know if I had to.
I also had to translate "Rendering Elements" into "Faire le rendu d'éléments" in the introduction paragraph, as the page isn't merged yet. @shinework if you translate this part to another text, please let me know 😄

Translate State and Lifecycle page to French

---

content/docs/components-and-props.md

It remains several questions about:
* Correctness of the translation
* `App` en haut de leur hiérarchie / `App` component at the very top.
* to be in the scope /  pour appartenir aux contexte d'exécution
* Render / Effectue le rendu
* Relevance not to translate:
* The exemple with `Avatar` and `Comment`, is it relevant to translate those components to understand the example ?
* Same question for the example with `user` and `author` (Line 174)
* Same question for the `sum` function (Line 240)
* Misc:
* Is it correct that i added `Essayer sur CodePen` ?
* ~~I notice some differences with current documentation on reactjs.org~~ EDIT: Not anymore with [#14](https://github.com/reactjs/fr.reactjs.org/pull/14)

Translation of "Components and Props" Doc page

---

content/docs/lists-and-keys.md

Translated the page "Lists and Keys" to French.

Translate Lists and Keys page to French

---

content/community/nav.yml
src/components/CodeEditor/CodeEditor.js
src/components/CodeExample/CodeExample.js
src/components/ErrorDecoder/ErrorDecoder.js
src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js
src/templates/components/NavigationFooter/NavigationFooter.js

Translation of all layout elements

---

content/docs/forms.md

Hello ! 👋
Voici un premier jet pour la page des formulaires https://reactjs.org/docs/forms.html

Traduction de la page "Forms"

---

content/docs/cdn-links.md

Bonjour,
Voici ma proposition de traduction de la page [CDN Links](https://reactjs.org/docs/cdn-links.html).
J'ai toutefois une hésitation sur le titre. J'ai mis `Liens du CDN`, mais est-ce la meilleure option ?

Translate "CDN Links" page

---

content/docs/create-a-new-react-app.md

Bonjour,
Voici ma traduction pour la page [Create a New React App](https://reactjs.org/docs/create-a-new-react-app.html).
Mes remarques / questions :
1. Y a t-il une bonne traduction pour `bundler` ? J'ai trouvé `empaqueteur` sur MDN, mais ils [ont aussi](https://developer.mozilla.org/fr/docs/Glossaire/Tree_shaking) `gestionnaires de regroupements de modules`, que je n'aime pas trop...
2. `Toolchain` a été traduit en `chaîne d'outils`. Existe-t-il une meilleure traduction ?

Translate "Create a New React App" page

---

content/docs/composition-vs-inheritance.md
content/docs/nav.yml

Bonjour à tous 👋 
Voici ma traduction de la page [Composition vs Inheritance](https://reactjs.org/docs/composition-vs-inheritance.html)
J'ai un peu hésité sur la traduction du titre en `Composition contre Héritage` ou `Composition et Héritage`. J'ai préféré le second choix qui me semblait plus harmonieux. C'est assez subjectif, je veux donc bien votre avis.

 Traduction de la page "Composition vs Inheritance"

---

content/docs/hello-world.md

Translation for Hello World

---

content/docs/nav.yml
content/docs/react-without-jsx.md

translated react-without-jsx

---

content/docs/conditional-rendering.md

conditionnal rendering

---

content/docs/lifting-state-up.md
content/docs/nav.yml

Translate the page "Lifting State Up".

Translate lifting-state-up

---

content/docs/reference-events.md

Bonjour,
Voici ma proposition de traduction pour la page [SyntheticEvent](https://reactjs.org/docs/events.html).
Quelques remarques / doutes :
1. J'ai laissé `wrapper` tel quel, je ne sais pas s'il y a une traduction plus adaptée.
2. Pour `Pooling`, j'ai utilisé partage (`Event pooling` => `Partage d'événement`). Pareil, si une meilleure traduction existe, j'adapterai.
3. J'ai traduit les termes `XXX Events` par `Événements de XXX` (`Keyboard Events` par `Événements de clavier`). Je ne sais pas si `Événements du clavier` ou plus simplement `Événements clavier` est à préférer ?
4. J'ai une hésitation sur la meilleure traduction pour `cross-browsers` : j'ai utilisé `inter-navigateur`, mais MDN privilégie [`navigateur croisé`](https://developer.mozilla.org/fr/docs/Learn/Tools_and_testing/Cros …

Synthetic events

---

content/docs/hooks-rules.md
content/docs/nav.yml

Bonjour 👋 
Voici la traduction de "Rules of Hooks".
C'est ma toute première traduction officielle. J'ai donc préféré rester dans les "clous" contrairement à d'habitude.
Dans l'attente de vos reviews 😅

🌐 Translate "Rules of Hooks" into French

---

content/docs/reference-react-dom-server.md

Translation of the API Reference "ReactDOMServer"

---

content/docs/nav.yml
content/docs/reference-dom-elements.md

Bonjour,
Voici ma proposition de traduction de la page [DOM Elements](https://reactjs.org/docs/dom-elements.html).
\o/

Translation for "Dom Elements"

---

content/warnings/dont-call-proptypes.md

Hésitation pour `crash` entre `planter` et `échouer`.
Je n'ai pas traduit les messages d'avertissement à l'intérieur des déclarations PropTypes.

Translation - Don't call proptypes

---

content/warnings/invalid-aria-prop.md
content/warnings/invalid-hook-call-warning.md
content/warnings/legacy-factories.md
content/warnings/refs-must-have-owner.md
content/warnings/special-props.md
content/warnings/unknown-prop.md

Translation of all warnings (except Don't call PropTypes, done already)

---

content/docs/hooks-custom.md

🌐 Translate "Building Your Own Hooks" into French

---

content/docs/error-boundaries.md

Bonjour,
Voici ma proposition de traduction pour la page [Error Boundaries](https://reactjs.org/docs/error-boundaries.html).
La traduction de `Error boundaries` n'est effectivement [pas simple](https://github.com/reactjs/fr.reactjs.org/pull/55#issuecomment-465330724), j'ai mis `Limiteur d'erreur` mais je ne suis pas vraiment satisfait.
Soit on trouve mieux, soit on laisse, soit on garde le terme anglais (en mettant une petite note de traduction au début).
/poke @tdd :)

Error boundaries

---

content/docs/faq-internals.md

Plusieurs points de discussion avant de soumettre une PR:
- `Internals` a été traduit par `fonctionnalités` mais je ne suis pas certaine de cette traduction
- `la gestion des événements et la mise à jour manuelle du DOM que **sinon** vous auriez dû utiliser pour créer votre application.` j'avoue ne pas vraiment être sûre de où placer `sinon` dans cette phrase.
- Doit-on traduire le concept de `React Fiber` et `Fiber` dans le dernier paragraphe ?
Merci.

Faq internals

---

content/docs/reconciliation.md

Hello,
Voilà ma traduction de la page [Reconciliation](https://reactjs.org/docs/reconciliation.html).
Bonne lecture !

Translate Reconciliation page

---

content/blog/2015-03-30-community-roundup-26.md
content/docs/integrating-with-other-libraries.md

Une hésitation sur la traduction de `unregister` en `désenregistrer` ?

Integrating with other libraries

---

content/docs/higher-order-components.md
content/docs/nav.yml

PR pour la traduction de la page [Higher-Order Components](https://reactjs.org/docs/higher-order-components.html).
Lundi 11 mars: 399/399 lignes **(100%)** :tada:
- "wrapped component" :arrow_right: souvent traduit "composant enfant"

Translate Higher-Order Components

---

content/docs/forwarding-refs.md
examples/forwarding-refs/customized-display-name.js
examples/forwarding-refs/fancy-button-ref.js
examples/forwarding-refs/fancy-button-simple-ref.js
examples/forwarding-refs/fancy-button.js
examples/forwarding-refs/log-props-after.js
examples/forwarding-refs/log-props-before.js

Translation of the “Forwarding Refs” page

---

content/docs/react-without-es6.md

Bonjour j'espère que vous passez tous un agréable week-end, 🙂
Voici ma proposition de traduction pour la page React Without ES6,
*Note*: je n'ai pas réussi à trouver une traduction un minimum correcte pour `Legacy` en ligne `180`,  des proposition ? 😅

Translation of all layout elements React Without ES6

---

content/docs/jsx-in-depth.md

Translation of the “JSX in Depth” page

---

content/docs/context.md
content/docs/nav.yml
examples/context/motivation-problem.js
examples/context/motivation-solution.js
examples/context/multiple-contexts.js
examples/context/reference-caveats-problem.js
examples/context/reference-caveats-solution.js
examples/context/theme-detailed-app.js
examples/context/theme-detailed-theme-context.js
examples/context/updating-nested-context-app.js
examples/context/updating-nested-context-context.js
examples/context/updating-nested-context-theme-toggler-button.js

Voici enfin ma PR pour la traduction du Contexte !
- J'ai rencontré plusieurs difficultés de traductions notamment sur les mots `Consumer`, `Provider` et même `Contexte`, je ne savais s'il fallait parfois garder les VO ou utiliser les VF, et je ne comprenais pas à quel moment il faut choisir de laisser les mots en majuscule ou en minuscule.
- Il y a certaines phrases qui sont très lourdes une fois traduites, et je ne suis pas contre un oeil nouveaux pour proposer de meilleures tournures.
- Dois-je aussi traduire la page `legacy-context.md` ?

Add French translation for Context

---

content/docs/implementation-notes.md

Traduction terminée, merci pour vos remarques

Translate "Implementation Notes" page

---

content/blog/2018-06-07-you-probably-dont-need-derived-state.md

Blog post translation (You probably don't need derived state)

---

content/blog/2016-07-13-mixins-considered-harmful.md

Salut @JeremiePat, je review ta propre trad aujourd'hui ! Voici un autre pavé pour le plaisir de tes yeux… 😜

Translation of the “Mixins Considered Harmful“ blog post

---

content/docs/how-to-contribute.md

Salut !
Voila ma première passe sur la traduction. Désolé pour le nom de commit etc. (Ce serait chouette de squah & merge cette PR pour avoir un message plus correct) je suis en voyage et ai du laisser mon ordinateur chez une amie, donc je fais tout sur mobile 😅
Ayant eu aussi une connexion limitée a internet ces derniers jours, donc je n'ai pas pu checker les PR précédentes non plus...
J'espère que c'est quand meme de bonne qualité 😀

Translated the "How to contribute" page

---

content/community/tools-debugging.md

Hello,
Voici ma traduction de la page https://reactjs.org/community/debugging-tools.html
J'ai changé la traduction de `(...) in the Chrome Developer Tools.` parce que ça me fait bizarre de parler de "Chrome Dev Tools" dans Firefox 😉

Translate Community/Tools/Debugging page

---

content/community/tools-routing.md

Hello,
Ma traduction de la page [Routing](https://reactjs.org/community/routing.html).

Translate Community/Tools/Routing page

---

content/community/tools-data-fetching.md

Hello,
Ma traduction pour https://reactjs.org/community/data-fetching.html

Translate Community/Tools/Data Fetching page

---

content/community/podcasts.md

 🌐Translation podcasts

---

content/blog/2017-07-26-error-handling-in-react-16.md

Après avoir traduit environ 1/3 de la page, je me suis  aperçu (par chance 😅) que le texte est quasiment identique que la PR #67.
Vu que le travail était déjà fait, et par souci d'homogénéité, j'ai repris le travail de @linsolas en y apportant de légères modifications dues aux différences présentes dans l'article du blog par rapport à la page de la documentation "Error Boundaries".

Blog post translation (Error Handling in React 16)

---

content/docs/refs-and-the-dom.md

Pas certain que se soit les refs qui doivent être référencées mais sans le verbe "être" il y a un problème de sens.

oubli du verbe être

---

content/blog/2015-12-18-react-components-elements-and-instances.md

Translate "React Components, Elements, and Instances" page

---

content/blog/2019-10-22-react-release-channels.md

Because 98% of the text is copy-pasted with the Release Channels page, and this latter one was already translated and approved, I'll self-approve this.

Translation of the Release Channels blog post

---

content/blog/2018-11-13-react-conf-recap.md

C'est ma première trad, soyez indulgent :)
J'ai essayé de suivre au mieux les conseils fournis par la documentation.
J'attends vos retours si certaines tournures ne semblent pas naturelles.
Je les corrigerai au plus vite!
J'ai mis quelques commentaires aux endroits où je sens qu'il y a potentiellement un problème de traduction.

Translation of the "2018-11-13-react-conf-recap" page

---

content/blog/2018-03-27-update-on-async-rendering.md

Je suis tombé sur un lien pointant vers la version "en" du blog en quand le "fr" semblait préférable.
Il me semble ne pas avoir vu de PR sur les liens en cours, aussi j’espère que cette première contribution suis bien les bonnes pratiques.

Redirect to the fr section of the blog

---

content/tutorial/nav.yml

Petite correction pour que l'intitulé du lien corresponde au titre du paragraphe : https://fr.reactjs.org/tutorial/tutorial.html#declaring-a-winner

Correction de intitulé d'un lien

---

content/docs/optimizing-performance.md

La libraire Immer s'écrit avec 2 "m".

Correction de l'intitulé d'un lien

---

content/docs/state-and-lifecycle.md

Il manque le 'r' dans this.timeID.

Correction nom d'une variable

---

content/blog/2017-09-08-dom-attributes-in-react-16.md

@tdd désolée du retard, cette traduction n'était complètement sortie de la tête ! Espérant que tu aies pu rattraper ton retard de relecture.

 🌐 Translation blog post 2017-09-08

---

content/blog/2018-09-10-introducing-the-react-profiler.md
content/docs/optimizing-performance.md

Si vous avez un moment sous 24h (je sais, je sais…) j'apprécierais votre relecture de ma trad pour l’article de blog sur le Profileur. /ping aux grand·e·s habitué·e·s : @juliettelofaro @lbelavoir @linsolas @forresst @LaureRC…
Je suis en train de traduire les articles de blog listés dans l'*issue* centrale (liés 2+ fois depuis les docs) ainsi que certains articles autres mais ayant moins de 2 ans.
Merci !

Traduction française de l'article de blog “Introducing the React profiler“

---

content/docs/hooks-reference.md

Fixing 2 very minor typos in the french translation :
"en tout sécurité" >> "en tout**e** sécurité"

Fixed 2 minor typo in french

---

content/versions.yml
src/site-constants.js

**What:**
fixes issue [#3663](https://github.com/reactjs/reactjs.org/issues/3663) : 
displays all versions in fr.reactjs.org/versions
Before fix:
After fix:
**How:** 
- update versions.yml with missing latest versions
- update version const in site-constants.js to latest version 17.0.2

fix: display all react versions in fr.reactjs.org/versions

---

content/docs/testing-recipes.md

Fix a typo in `testing-recipes.md`.
A reference to `react-dom/rest-utils` import should be replaced by `react-dom/test-utils`.

Fix a typo in testing-recipes.md

---

content/docs/forwarding-refs.md

Fix small typo related to issue #297

Fix small typo, issue #297

---

content/community/courses.md

As reported [in this issue](https://github.com/reactjs/reactjs.org/issues/3754) from the reactjs.org repo, we had an old deprecated link to Openclassrooms.
This link wasn't dead as described: Openclassrooms redirects to their new course.
Anyway I updated the link.
I also updated the description of the Openclassrooms course : in this new course, there is no component testing as it may have been before.

Fix dead link to openclassrooms React course #3754

---

content/docs/reference-react-component.md

- Fix small typos in `docs/reference-react-component.md`

Fix typos in docs/reference-react-component.md

---

content/docs/reconciliation.md

componentWillMount and componentWillReceiveProps are no longer supported by React
Same as https://github.com/reactjs/reactjs.org/pull/3475

Add UNSAFE_ prefix to legacy lifecycles

---

src/components/DocsFooter.tsx
src/components/Layout/Feedback.tsx
src/components/Layout/Footer.tsx
src/components/Layout/Page.tsx
src/components/MDX/MDXComponents.tsx
src/components/MDX/Sandpack/CustomPreset.tsx
src/components/MDX/Sandpack/DownloadButton.tsx
src/components/MDX/Sandpack/OpenInCodeSandboxButton.tsx
src/components/MDX/Sandpack/ResetButton.tsx

La structure des docs devrait encore pas mal changer, et l'équipe noyau nous demande de ne pas trop traduire la nav (sidebar, footer…) pour le moment.
Toutefois, j'estime que certains éléments ne devraient plus bouger de façon significative, voire plus du tout, et méritent donc une traduction d'entrée de jeu, notamment pour lisser la perception de langue au sein d'une même page de doc :
- Les en-têtes principaux de structure de nav (déjà traduits en en-tête pour #449), ici dans le footer
- Le widget de feedback positif/négatif d'utilité de page (en bas à gauche en desktop)
- Les éléments de fin de page (appel à réponse au sondage sur les nouvelles docs, liens Précédent / Suivant)
- Les éléments d'UI des sandboxes (boutons Télécharger, Réinitialiser, Fork, bascules Voir plus / moins)
- Les …

UI : traduction d'éléments jugés suffisamment stables

---

src/content/learn/managing-state.md
src/sidebarLearn.json

Voilà ma PR pour la page Managing State, n'hésitez pas si vous avez des retours à faire dessus

Traduction of the "Managing state" page

---

src/content/reference/react/Fragment.md

Hello, voici ma PR pour la traduction de la page "Fragment", j'espère que c'est ok, ouverte aux retours 😀

Translation of the "Fragment" page

---

src/components/MDX/MDXComponents.tsx
src/content/learn/reacting-to-input-with-state.md

Voilà ma PR pour cette nouvelle page, j'ai tenu compte des remarques de la précédente, il devrait y avoir moins d'erreurs, merci pour vos reviews.

Traduction of the "Reacting to input with state" page

---

src/content/reference/react/index.md

Traduction de la page index de `react: hooks`

react:Hooks index page translation

---

src/content/reference/react/Profiler.md

Hello, voici ma PR pour la page `Profiler` 😁

Translation of the "Profiler" page

---

src/content/reference/react/useId.md

Salut 👋 ! Voici ma PR pour la traduction de la page `reference/react/useId` de la documentation.
Merci aux maintainers pour le glossaire et les bonnes pratiques

Translation of the "useId" page from API references

---

src/content/learn/escape-hatches.md
src/sidebarLearn.json

Une relecture serait la bienvenue d'ici la fin du weekend, en plus de ma propre repasse déjà faite.

Translation: Escape Hatches (index page)

---

src/content/learn/removing-effect-dependencies.md

Je laisse ça là quelques jours si une review vous dit, ensuite je mergerai. Une repasse interne complète a déjà été faite.

Translation: Removing Effect Dependencies

---

src/content/learn/editor-setup.md
src/sidebarLearn.json

PR pour la traduction de la page "Editor Config"

Translation of the "Editor Config" page

---

src/content/learn/add-react-to-an-existing-project.md
src/sidebarLearn.json

🎉 Salut @tdd ! 
Je voulais vous informer que j'ai terminé la trad de la page 'Add React to an Existing Project'. 
Prêt pour votre revue.

Translation of the 'Add React to an Existing Project' page

---

public/images/docs/illustrations/i_import-export.svg
src/content/learn/importing-and-exporting-components.md
src/sidebarLearn.json

Traduction française de la page [Importing and Exporting Components](https://react.dev/learn/importing-and-exporting-components).

Translation of the “Importing and Exporting Components” page

---

src/content/learn/updating-objects-in-state.md

Traduction française de la page [Updating Objects in State](https://react.dev/learn/updating-objects-in-state).

Translation of the “Updating Objects in State” page

---

src/content/learn/preserving-and-resetting-state.md

Translation of Preserving and Resetting State

---

src/content/reference/react/useState.md

Bonjour ! 
Voici le premier jet de la traduction de `useState`. J'ai traduis approximativement 300 lignes pour commencer. J'ai bien conscience que c'est un morceau complexe et crucial, donc j'y vais avec parcimonie ! :wink: 
J'ai quelques questions concernant du vocabulaire : 
- Comment traduire **`set` function** ? **Fonction `set`** me semble être le plus proche de ce qu'il y a dans la documentation Legacy. 
- **Checkbox** => **Case à cocher** me semble un peu verbeux, mais ça me semble être le plus proche :smile: 
- **boolean** => dans le doute, **booléen** me semble être la bonne traduction, mais je ne suis pas à 100% sûre !
- **Updater function** => c'est celui qui m'a fait m'arrêter pour ce soir :laughing: **Fonction de mise à jour** ? Mais lorsque la documentation mentionne …

Translation of the 'useState' page

---

src/content/reference/react-dom/components/option.md

Translation of "<option>" page

---

TRANSLATORS.md
src/content/reference/react-dom/createPortal.md

Un des composants de `react-dom` que j'adore utiliser 🛩️

Translation of create portal

---

TRANSLATORS.md
src/content/reference/react/memo.md

here you will see the memo page for the french translation

add translation of memo page

---

TRANSLATORS.md
src/content/blog/index.md
src/content/community/acknowledgements.md
src/content/community/conferences.md
src/content/community/docs-contributors.md
src/content/community/index.md
src/content/community/meetups.md
src/content/community/team.md
src/content/community/versioning-policy.md
src/content/community/videos.md
src/sidebarCommunity.json

Pretty much **all of community, except:**
- Details of conferences and meetups (dates, in-person/remote, cities, etc.)
- Descriptions of React Core team members
- Titles and descriptions of videos
- Versioning policy
- Blog posts
This smoothes up the FR experience, and does provide translation for contributors and acknowledgements, which I thought was a priority.

Partial translation of community contents

---

TRANSLATORS.md
src/content/reference/react-dom/findDOMNode.md

Here you will find the french translation of `findDOMNode` page

add french translation for findDOMNode

---

src/content/reference/react/Profiler.md

Hello @tdd  !
Je lisais la documentation sur le `Profiler` quand j'ai lu `ɗ un` dans la phrase
> Elle reçoit des informations indiquant ce qui a fait l’objet **ɗ un** rendu et quel temps ça a pris.
Je me suis dit que c'est surement une faute de frappe et que ça devrait être `d'un`. Il manquait l'apostrophe et le `ɗ` n'est pas le bon.
**Cette PR replace `ɗ un` par `d'un`.**
Issue: https://github.com/reactjs/fr.react.dev/issues/634

Chore(docs): fix typo in `Profiler` docs

---

src/content/reference/react/useLayoutEffect.md

Hello,
Cette PR corrige une typo dans le fichier useLayoutEffect.md, il manquait un 't' à useLayoutEffect dans la page.

Chore(docs): fix typo in useLayoutEffect.md

---

src/content/reference/react/experimental_useEffectEvent.md

This PR fixes a typo in the french version of experimental_useEffectEvent.md

Fix typo on experimental_useEffectEvent.md

---

src/content/learn/keeping-components-pure.md

The original text in english :
__ Rendering can happen at any time, **so** components should not depend on each others’ rendering sequence. __
=> the traduction of **so** is "ainsi", not "aussi".

Fix wrong traduction "aussi" -> "ainsi"

---

src/content/learn/responding-to-events.md

fix wrong orthographe : "losqu'on" => "lo**r**squ'on"

fix wrong orthographe : "losqu'on" => "lorsqu'on"
